development: &dev
  adapter: postgresql
  encoding: unicode
  database: ls_development
  host: <%= ENV['DB_HOST'] || "172.17.0.2"%>
  pool: 20
  username: postgres
  password: postgres
test: &test
  <<: *dev
  database: ls_test

production:
  <<: *dev
  database: ls_production

cucumber:
  <<: *test
